function [fitresult, gof] = createFit(train_delT, train_HR, train_Rs)
%CREATEFIT(TRAIN_DELT,TRAIN_HR,TRAIN_RS)
%  Create a fit.
%
%  Data for 'modeloDos' fit:
%      X Input : train_delT
%      Y Input : train_HR
%      Z Output: train_Rs
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 08-Jan-2019 15:29:22


%% Fit: 'modeloDos'.
[xData, yData, zData] = prepareSurfaceData( train_delT, train_HR, train_Rs );

% Set up fittype and options.
ft = fittype( 'a*(1+b*y)*(1-exp(-c*x^n))', 'independent', {'x', 'y'}, 'dependent', 'z' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.37758972291541 0.486999130246316 0.291802457255874 0.823457828327293];

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.
figure( 'Name', 'modeloDos' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'modeloDos', 'train_Rs vs. train_delT, train_HR', 'Location', 'NorthEast' );
% Label axes
xlabel train_delT
ylabel train_HR
zlabel train_Rs
grid on
view( -6.3, 3.6 );


