function graficar(X1, Y1, Z1, S1, SolRatio1)
%CREATEFIGURE(X1, Y1, Z1, S1, SolRatio1)
%  X1:  scatter3 x
%  Y1:  scatter3 y
%  Z1:  scatter3 z
%  S1:  scatter3 s
%  SOLRATIO1:  scatter3 c

%  Auto-generated by MATLAB on 08-Jan-2019 14:42:44

% Create figure
figure1 = figure('Name',...
    'Datos de radiación solar en el valle de sacramento');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create scatter3
scatter3(X1,Y1,Z1,S1,SolRatio1);

% Create zlabel
zlabel('Radiación solar');

% Create ylabel
ylabel('Año');

% Create xlabel
xlabel('Dia del año');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-16.3922082548273 353.607791745173]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[2000.38431740157 2010.38431740157]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[-0.0313106608811002 0.9686893391189]);
view(axes1,[-37.5 13.9999999999999]);
grid(axes1,'on');
% Create colorbar
colorbar('peer',axes1);

